config/routes.rb
Rails.application.routes.draw do
  
  resources :relationships

  get 'users/index'

  get 'users/show'

  get 'users/profile'




  devise_for :users

  resources :users do
    member do
      # gets following and followers for a certain user
      get :following, :followers
    end
  end




resources :pins do
  collection do
    get "search"
  end
    member do
        get 'like', to: 'pins#upvote'
        get 'dislike', to: 'pins#downvote'
      end
  resources :comments
end


root "pins#index"



get 'profile', to: 'users#profile'




resources :relationships, only: [:create, :destroy]

#pins controller and index action

end

app/models/pin.rb
class Pin < ActiveRecord::Base

	# searchkick
	acts_as_votable
	
	belongs_to :user

  	

	has_many :comments, dependent: :destroy

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	
	before_action :authenticate_user!, except: [:index, :show]

	# def search
	# 	if params[:search].present?
	# 		@pins = Pin.search(params[:search])
	# 	else
	# 		@pins = Pin.all
	# 	end
	# end

	def show
    	@comments = Comment.where(pin_id: @pin)
  	end

	def index
		#put newest first
		@pins = Pin.all.order("created_at DESC")	
	end




	def create
		#have each pin assigned to current_user
		@pin = current_user.pins.build(pin_params)
			if @pin.save
				redirect_to @pin, notice: "Successfully created new pin!"
			else
				render 'new'
			end
	end



	def new
		#have each pin assigned to current_user
		@pin = current_user.pins.build
	end


	def edit
	end


	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Successfully Updated!"
		else
			render 'edit'
		end
	end



	def destroy
		@pin.destroy
		redirect_to root_path
	end


	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	def downvote
	    @pin.downvotevote_by current_user
	    redirect_to :back
 	end


	private

		def pin_params
			params.require(:pin).permit(:title, :description, :image)
		end

		def find_pin
			@pin = Pin.find(params[:id])
		end



end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for @pin do |f| %>
	<% if @pin.errors.any? %>
			<div id="errors">
	      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this post from being saved:</h2>

	      <ul>
	      <% @pin.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	<% end %>      


<div class = "form-group">
    <%= f.input :image, input_html: { class: 'form-control' }, placeholder: 'Choose a picture' %>
</div>

<div class = "form-group">
    <%= f.input :title, input_html: { class: 'form-control' }, placeholder: 'Title please' %>
</div>

<div class = "form-group">
    <%= f.input :description, input_html: { class: 'form-control' }, placeholder: 'Please add a description' %>
</div>





<br> 

<div class="actions">
   <%= f.button :submit, class: "btn btn-primary" %>
</div>


<% end -%>

app/views/pins/_new_pin.html.erb
<h1><%= link_to "Add Post", new_pin_path, class: "btn btn-default btn-lg" %></h1>

app/views/pins/_test.html.erb
<% @comments.each do |comment| %>
<div class="comment-wrap">
				<div class="photo">
						<div class="avatar">
							<% if current_user.avatar != nil%>
							<ul class="list-unstyled">
								<li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
							</ul>
							<%end%>
						</div>
				</div>
				<div class="comment-block">
						<p class="comment-text"> <%= comment.content %> </p>
						<div class="bottom-comment">
								<div class="comment-date"><%= time_ago_in_words(comment.created_at) %></div>
								<br> Submitted by: <%= comment.user.username %>	
						</div>
				</div>
</div>
<%end%>

app/views/pins/edit.html.erb
<div class = "col-md-6 col-md-offset-3">
	<div class = "row">
		<div class="panel panel-default">
			<div class = "panel-heading">
				<h1> Edit Memento </h1>
			</div>

			<div class = "panel-body">
				<strong class ="center"> Current Image </strong><br>
				<%= link_to image_tag(@pin.image.url(:medium)) %>
			</div>
				<%= render 'form' %>

				<%= link_to 'Cancel', pin_path %>
		</div>
	</div>
</div>

app/views/pins/index.html.erb
<!-- <h1>this is the index placeholder <h1> -->
<!-- <div class = "container">
<div class = "col-md-offset-0"> -->
		<!-- list out all PINS -->
			<% @pins.each do |pin| %>
	<div id="pins" class="transitions-enabled infinite scroll centered clearfix">

<!-- display user info -->
				<div class="box panel panel-default">

					
						<%= link_to (image_tag pin.image.url), pin %> 

						<h2><%= link_to pin.title, pin %></h2>
						<h4><%= pin.description.first(120) %></h4>
						
						<p class="user">Submitted by: 
							<% if pin.user.username == nil%>
								<%= pin.user.email %>
							<% else %>
								<%= link_to pin.user.username, pin.user%>
							<% end %>
							<div class ="btn-group pull-right">
								<span>
					              <i class="fa fa-comments-o"></i>
					              <%= pin.comments.count %>
					            </span>
					            <span>
					              <i class="fa fa-thumbs-o-up"></i>
					              <%= pin.get_likes.size %>
					            </span>
							</div>
						</p>
				</div>
				<% end %> 

</div>

			
	
<!-- </div>
</div> -->

app/views/pins/new.html.erb
<div class = "col-md-6 col-md-offset-3">
	
	<div class="row">

		<div class="panel panel-default">


			<div class = "panel-heading">
				<h1> New Memento </h1>
			</div>

			<div class = "panel-body">
				<%= render partial: 'form' %>

				<br>

				<%= link_to 'Back', root_path %>
			</div>

app/views/pins/search.html.erb
<div id="pins" class="transitions-enabled infinite scroll centered clearfix">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url(:medium), class: 'image'), pin %>
        	<h2><%= link_to pin.title, pin %></h2>
			
        <p class="user">
          Submitted by: 
  				<% if pin.user.username == nil%>
  					<%= pin.user.email %>
  				<% else %>
  					<%= pin.user.username%>
  				<% end %>
  			</p>

    </div>
  <% end %>
   </div>
  </div>	
</div>

app/views/pins/show.html.erb
<!-- <div class = "col-md-6 col-md-offset-3"> -->
<div id="pin_show" class="row">
<div class="col-md-offset-2 col-md-8">
	<div class="panel panel-default">
		<div class="panel-heading pin_image">


 					<%= image_tag(@pin.image.url) %>
 					<%= time_ago_in_words(@pin.created_at) %>






			<div class="panel-body">	
				<h1> <%= @pin.title %> </h1>
				<p class ="description"><%= @pin.description %></p>
				
				<h2><%= pluralize(@pin.comments.count, "comment") %></h2>
				
				<% @comments.each do |comment| %>
				<div class="comment-wrap">
					<div class="photo">
						<div class="avatar">
							<% if comment.user.avatar != nil%>
							<ul class="list-unstyled">
								<li class="image-comment"><%= link_to image_tag(comment.user.avatar.url(:thumb)), comment.user %></li>
							</ul>
							<%end%>
						</div>
					</div>
					<div class="comment-block">
						<p class="comment-text"> <%= comment.content %> </p>
						<div class="bottom-comment">
								<div class="comment-date"><%= time_ago_in_words(comment.created_at) %></div>
								<br> Submitted by: <%= comment.user.username %>	
						</div>
					</div>
				</div>
				
				<%end%>	
				<%= render 'comments/form' %>
			</div>








		<div class = "panel-footer">
			<div class = "row">	
					<div class="col-md-6">
						<p class ="user">Submitted by: 
							<% if @pin.user.username == nil%>
								<%= @pin.user.email %>
							<% else %>
								<%= @pin.user.username%>
							<% end %> </p>
					</div>
				


<!-- < link_to 'Back', root_path %> -->
		<div class="col-md-6">
			<div class ="btn-group pull-right">
				<%= link_to like_pin_path(@pin), method: :get, class: "btn btn-default" do %>
					<i class="fa fa-thumbs-o-up "></i><%= pluralize(@pin.get_upvotes.size, " Like") %>
				<% end %>
				<%= link_to dislike_pin_path(@pin), method: :get, class: "btn btn-default" do %>
					<i class="fa fa-thumbs-o-down "></i><%= pluralize(@pin.get_downvotes.size, " Dislike") %>
				<%end%>	


				<% unless @pin.user != current_user %>
				<%= link_to 'Edit', edit_pin_path, class: "btn btn-default"  %> 
				<%= link_to 'Delete', pin_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default"%>
				<% end %>
			</div>
		</div>

</div>
	</div>
		</div>
			</div>
							</div>
								</div>