config/routes.rb
Rails.application.routes.draw do
  
  resources :relationships

  get 'users/index'

  get 'users/show'

  get 'users/profile'




  devise_for :users

  resources :users do
    member do
      # gets following and followers for a certain user
      get :following, :followers
    end
  end




resources :pins do
  collection do
    get "search"
  end
    member do
        get 'like', to: 'pins#upvote'
        get 'dislike', to: 'pins#downvote'
      end
  resources :comments
end


root "pins#index"



get 'profile', to: 'users#profile'




resources :relationships, only: [:create, :destroy]

#pins controller and index action

end

app/models/user.rb
class User < ActiveRecord::Base



  # searchkick

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy

  has_many :comments, dependent: :destroy
  # attr_accessor :login
  # validates_uniqueness_of :username
  validates_presence_of :username
  validates :username, length: { in: 4..20 }

  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login }]).first
  #   else
  #     where(conditions).first
  #   end
  # end

  
#avatar image & add the s3 pclip
  has_attached_file :avatar, :styles => { :medium => "619x223>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png", :storage => :s3, :bucket => ENV['S3_BUCKET_NAME']
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


# bgphoto image
has_attached_file :bgphoto, :styles => { :normal => "718x237" }, :default_url => "/images/:style/missing.png", :storage => :s3, :bucket => ENV['S3_BUCKET_NAME']
validates_attachment_content_type :bgphoto, :content_type => /\Aimage\/.*\Z/



# Follower/followed
#relationships - followers
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy                                  
  # has_many followeds is unusual so redefine via source                                
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower




# News Feed of followers


  #follow methods
def follow (other_user)
  active_relationships.create(followed_id: other_user.id)
end


def unfollow (other_user)
  active_relationships.find_by(followed_id: other_user.id).destroy
end

def following?(other_user)
  following.include?(other_user)
end
       
def logged_in?
    current_user != nil
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]


  def edit
  end

  def new
  	@user = User.new
  end

  def index
  	@users = User.all.order("created_at DESC")
  end

  def show
  	@user = User.find(params[:id])
  end

  def profile
  	@user = User.find(params[:id])
  end



  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


	def update
	    respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to @user, notice: 'User was successfully updated.' }
	        format.json { render :show, status: :ok, location: @user }
	      else
	        format.html { render :edit }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	  end


 def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
 end

 def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :content, :tagline, :avatar)
    end

end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <div class ="btn btn-default btn-lg">
  	<%= f.submit "Follow" %>
  </div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user%>
<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
  <% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
	<% if @user.errors.any? %>
			<div id="errors">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	<% end %>    

  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_area :tagline %>
  </div>

 <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_search.html.erb
<div class="row">
<% @users.each do |u| %>
	    <div class="col-sm-6 col-md-offset-3">
	    	<% if u.avatar != nil %>
	    		<%= u.avatar, u %>
	    		<%= u.username, u%>
	    	<% else %>
	    		<%= u.username, u %>
	    	<% end %>
			    <%if u.pin != nil%>
				      <div class="thumbnail">
				        <%= link_to (image_tag u.pin.image.url(:medium), class: 'image'), u %>
				        <div class = "col-sm- col-md-offset-5">
				        	<h2><%= link_to u.pin.title, u %></h2>
							<p class="user">Submitted by: 
								<% if user.username == nil%>
									<%= user.email %>
								<% else %>
									<%= user.username%>
								<% end %>
							</p>
				     	</div>
				<% end %>
		<% end %>
</div>
</div>	
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<a href = "<%= following_user_path(@user) %>">
	<strong id ="following" class= "stats">
	<%= @user.following.count %>
	</strong>
following
</a>
<a href = "<%= followers_user_path(@user) %>">
	<strong id ="followers" class= "stats">
	<%= @user.followers.count %>
</strong>
followers
</a>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <div class ="btn btn-lg btn-default">
  	<%= f.submit "Unfollow"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class = "col-md-4 col-md-offset-6 ">
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<div class ="container">






<% @users.each do |user| %>
<%= link_to user do %>
<div class="flip-container" id="dean">
    <div class="flip-card">
      <!-- FRONT FACE -->
    <div class="front face">
      <% if user.avatar.present?%>
          <%= image_tag(user.avatar, class: "indexprofileimg") %>
      <% else %>
         <img src = "../../assets/gravatar.jpg" class = "indexprofileimg">
      <% end %>
    </div>

  <!-- BACK FACE -->
    <div class="back face">
      <h4> <%= user.username %> </h4>
        <% if user.content.present? %>
          <p><%= user.content.first(30) + "..." %></p>
        <% else %>
          <p> <%= "Woops. Nothing here." %>
        <% end %>
    </div>

  </div>
</div>
<% end %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
assdada

app/views/users/show.html.erb
<div class="content-profile-page">
	


  <div class="profile-user-page card">
    <div class="img-user-profile">
   	<!-- Profile image and Background photo -->
      <% if @user == current_user %>  
        <%= link_to(edit_user_registration_path) do %>
        <!-- BACKGROUND photos -->
              <% if current_user.bgphoto.present? %>
                <%= image_tag(current_user.bgphoto.url(:normal), class: "profile-bgHome") %>
              <% else %>
                  <img class="profile-bgHome" src="https://download.unsplash.com/34/ddTzoX58Q153kjaitXl4_ny.jpg" style = "width:100%" />
              <% end %>

        <!-- AVATAR photos -->
              <% if @user.avatar.present?%>
                  <%= image_tag(@user.avatar.url(:thumb), class: "avatar") %>
              <% else %>
                  <img src = "../../assets/gravatar.jpg" class = "avatar"/>
              <% end %>

        <% end %>   

 <!-- NOT CURRENT USER -->
    <% else %>
      <!-- BACKGROUND photos -->
            <% if @user.bgphoto.present? %>
              <%= image_tag(@user.bgphoto.url(:normal), class: "profile-bgHome") %>
            <% else %>
                <img class="profile-bgHome" src="https://download.unsplash.com/34/ddTzoX58Q153kjaitXl4_ny.jpg" style = "width:100%" />
            <% end %>
      <!-- AVATAR photos -->
            <% if @user.avatar.present?%>
                <%= image_tag(@user.avatar.url(:thumb), class: "avatar") %>
            <% else %>
                <img src = "../../assets/gravatar.jpg" class = "avatar">
            <% end %>
    <% end %>
  </div>



     <!-- Follower user -->

     <% unless @user == current_user %>
          <%= render 'follow_form' if current_user != nil %>
     <% end %>




    <!-- Profile Description -->
          <br>
          <br>
          <div class="user-profile-data">
            <h1> </h1>
            <p> 
              <% if @user.tagline.present?%>
                <%= @user.tagline%> 
              <% else %>
                <% if @user == current_user %>
                  <%= link_to "Write Something", edit_user_path(@user)%>
                <% else %>
                  Nothing to See!
                <% end %>
              <% end %> 
              </p>
          </div> 



          <div class="description-profile"> 
            <% if @user.content.present?%>
                <%= @user.content%> 
            <% else %>
                <% if @user == current_user %>
                    <%= link_to "Write Something", edit_user_path(@user)%>
                <% else %>
                    No content yet...
                <% end %>
            <% end %> 
          </div> 
          <br>





	<!-- User stats: followers, following, pins-->
       <ul class="data-user">
        <li><a><strong><%= @user.pins.count %></strong><span>Memes</span></a></li>
        <li><a><strong><%= @user.comments.count %></strong><span>Comments</span></a></li>
        <li><a><strong> <%= @user.following.count %> / <%= @user.followers.count %> </strong><span>Following/Followers</span></a></li>

       </ul>
      </div>
  </div>



  <!-- User Posts' Images -->
<div class = "container">  
  <div class ="col-md-6 col-md-offset-4">
    <h1> <b>Your Posts on Dumo<b> </h1>
    <br>
  </div> 
  <div class ="col-md-6 col-md-offset-5">
    <% if @user.pins.present? %>
        <% @user.pins.each do |pin|%>
          <%= link_to (image_tag(pin.image.url(:thumb))), pin %>
        <% end %>
    <% else %>
        <%= render 'pins/new_pin' %>
    <% end %>
  </div>
</div>  

app/views/users/show_follow.html.erb
<div class = "container">
<div class ="col-md-3">
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= current_user.username %></h1>
      <span><%= link_to "view my profile", current_user %></span>
    </section>
    <section class="stats">
      <%= render 'stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>
</div>
</div>
</div>